Backend/edtech/addpost/urls.py
from django.urls import path

from . import views

app_name = 'addpost'
urlpatterns = [
    path('createpost/', views.createpost, name='createpost'),
    path('createprojpost/', views.createprojpost, name='createprojpost'),
]

Backend/edtech/createclass/urls.py
from django.urls import path

from . import views

app_name = 'createclass'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('create_new_class/', views.create_new_class, name='create_new_class'),
    path('<int:post_id>/deletepost/', views.deletepost, name='deletepost'),
    path('<int:proj_id>/removeproj/', views.removeproj, name='removeproj'),
]

Backend/edtech/createproject/urls.py
from django.urls import path

from . import views

app_name = 'createproject'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('create_new_project/', views.create_new_project, name='create_new_project'),
    path('<int:proj_id>/addprojtoclass/', views.addprojtoclass, name='addprojtoclass'),
    path('home/', views.home, name='home'),
    path('<int:proj_id>/proj_detail/', views.proj_detail, name='proj_detail'),
    path('<int:proj_id>/student_proj_detail/', views.student_proj_detail, name='student_proj_detail'),
]

Backend/edtech/edtech/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('addpost/', include('addpost.urls')),
    path('createproject/', include('createproject.urls')),
    path('createclass/', include('createclass.urls')),
    path('scrapenews/', include('scrapenews.urls')),
    path('admin/', admin.site.urls),
]

Backend/edtech/scrapenews/urls.py
from django.urls import path

from . import views

app_name = 'scrapenews'
urlpatterns = [
    path('home', views.index, name='index'),
    path('home2', views.index2, name='index2'),
    path('log_link/', views.log_link, name='log_link'),
    path('cognitivehome/', views.cognitivehome, name='cognitivehome'),
    path('cognitive_questionnaire/', views.cognitive_questionnaire, name='cognitive_questionnaire'),
    path('demo_home',views.demo_home, name='demo_home'),
]

Backend/edtech/createproject/models.py
from django.db import models
from django.core.validators import int_list_validator
from django.forms import ModelForm
from django import forms

# Create your models here...
class Projects(models.Model):
    def __str__(self):
        return self.Title
    Title = models.TextField()
    Short = models.TextField()
    Long = models.TextField() 
    #Image = models.FileField()
    #Image_data = models.BinaryField(null=True)
    Subjects = models.CharField(max_length=255)
    Class_size = models.TextField() 
    Group_size = models.TextField() 
    Level = models.CharField(max_length=255)
    Hours_estimated = models.IntegerField()
    Virtual = models.TextField()
    Locations = models.CharField(max_length=255)
    Start_date = models.DateField(blank=True, null=True)
    End_date = models.DateField(blank=True, null=True)
    Partner = models.CharField(max_length=255, default='GeorgiaTech')
    ClassNum = models.IntegerField(default=0)

class SubjectList(models.Model):
    def __str__(self):
        return self.Name
    Name = models.CharField(max_length=255)
    Abbreviation = models.CharField(max_length=3)

class StudentLevel(models.Model):
    def __str__(self):
        return self.Level
    Level = models.CharField(max_length=255)
    Abbreviation = models.CharField(max_length=3)

LEVELS = (
    ('E','Elementary'),
    ('M', 'Middle'),
    ('H', 'High'),
    ('U', 'Undergrad'),
    ('G', 'Grad'),
)
SUBJECTS = (
    ('ES','Environmental'),
    ('MA', 'Math'),
    ('B', 'Biology'),
    ('C', 'Chemistry'),
    ('P', 'Physics'),
    ('ME', 'Mechanical'),
    ('CS', 'Computer Science')
)
# Model Forms
class ProjectForm(ModelForm):
    Level = forms.MultipleChoiceField(choices = LEVELS)
    Subjects = forms.MultipleChoiceField(choices = SUBJECTS)
    class Meta:
        model = Projects
        fields = '__all__'#['Title','Short','Long','Image','Image_data','Subjects','Class_size','Group_size','Level','Hours_estimated','Virtual','Locations','Start_date','End_date']

Backend/edtech/createproject/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Projects, SubjectList, StudentLevel, ProjectForm
from addpost.models import ProjPostList
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from datetime import date

# Create your views here.
def index(request):
    project_list = Projects.objects.order_by('-Start_date')
    context = {'project_list': project_list}
    return render(request, 'createproject/index.html', context)


def keychecker(D, key):
    if key in D:
        return D[key]
    else:
        if 'date' in key:
            return date.fromisoformat('1970-01-01')
        else:
            return ''

def results(request):
    filters = request.GET
    if len(filters) == 0:
        project_list = Projects.objects.order_by('Start_date')
    else:
        project_list = Projects.objects.order_by('Start_date')\
                        .filter(Subjects__contains=keychecker(filters,'Subjects'),\
                        Partner__icontains=keychecker(filters,'Partner'),\
                        Level__contains=keychecker(filters,'Level'),\
                        Start_date__range= [keychecker(filters,'Start_date_0'),keychecker(filters,'Start_date_1')],\
                        )
                
    context = {'project_list': project_list}
    return render(request, 'createproject/results.html', context)

def addprojtoclass(request, proj_id):
    proj = get_object_or_404(Projects, pk=proj_id)
    proj.ClassNum = 1
    proj.save()

    return HttpResponseRedirect(reverse('createclass:home'))

def create_new_project(request):
    context = {}
    form = ProjectForm(request.POST or None)
    print(form)

    if form.is_valid():
        print(form)
        form.save()

    context['form'] = form
    return HttpResponseRedirect(reverse('createproject:home'))

def home(request):
    project_list = Projects.objects.order_by('-Start_date').filter(Partner='KevinCo')
    context = {'project_list': project_list}
    return render(request, 'createproject/partner_home.html', context)

def proj_detail(request, proj_id):
    proj = get_object_or_404(Projects, pk=proj_id)
    latest_posts = ProjPostList.objects.filter(ProjKey=proj_id).order_by('-PostDate')[0:30]
    context = {}
    context['proj'] = proj
    context['latest_posts'] = latest_posts

    return render(request, 'createproject/proj_detail.html', context)

def student_proj_detail(request, proj_id):
    proj = get_object_or_404(Projects, pk=proj_id)
    latest_posts = ProjPostList.objects.filter(ProjKey=proj_id).order_by('-PostDate')[0:30]
    context = {}
    context['proj'] = proj
    context['latest_posts'] = latest_posts

    return render(request, 'createproject/student_proj_detail.html', context)

Backend/edtech/createproject/templates/createproject/index.html
  <!DOCTYPE html>
  <html lang="en">
  
  <!-- Jquery scripts -->
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  
  <head>
    <meta charset="ut 8">
    {% load static %}
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>Create a Project</title>
  </head>
  
  <body>
    
    <div class = "wrapper">
      <div class = "nav-bar" id="partner-nav-bar">
        <h1 class="header"> WeMinari </h1>
        <ul>
          <p></p>
          <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
          <li><a href="{% url 'createproject:index' %}">Create New Project</a></li>
          <li><a href="{% url 'createproject:home' %}">Home</a></li>
        </ul>
      </div>
    </div>
    
    <!-- Header -->
    <div class ="title">
      <h1> Create Your Project, KevinCo. </h1>
    </div>
    
    <form action="create_new_project/" method="POST">
      {% csrf_token %}
      <div class="container">
        <!-- <h1>Register</h1> -->
        <p>Please fill in this form to create a project.</p>
        <hr>
        <input type="hidden" name="ClassNum" value="0">
        <label for="Partner"><b>Partner Name</b></label>
        <input type="text" placeholder="Enter Your Organization's Name" name="Partner" id="Partner" required>

        <label for="Title"><b>Project Name</b></label>
        <input type="text" placeholder="Enter Project Name" name="Title" id="Title" required>
        
        <label for="Short"><b>Short Project Description</b></label>
        <textarea rows = "3"  name = "Short" id="Short" placeholder="Brief Summary of Project (Max 250 Char)." maxlength="250" required></textarea><br>
        
        <label for="Long"><b>Full Project Description</b></label>
        <textarea rows = "8"  name = "Long" id="Long" placeholder="Full Details of Project..." required></textarea><br>
        
        <label for="Subjects"><b>Subjects </b></label>
        <p>(Select all that apply)</p>
        <div class="checklist">
          <input type="checkbox" id="Subjects" name="Subjects" value="ES">
          <label for="Subjects"> Environmental Sustainability </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="MA">
          <label for="Subjects"> Mathematics </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="B">
          <label for="Subjects"> Biology </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="C">
          <label for="Subjects"> Chemistry </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="P">
          <label for="Subjects"> Physics </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="ME">
          <label for="Subjects"> Mechanical Engineering </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="CS">
          <label for="Subjects"> Computer Science </label><br>
        </div>
        
        <label for="Class_size"><b> Classroom Size Desired </b></label>
        <div class = "checklist">
          <input type="radio" id="Class_size" name="Class_size" value="tiny">
          <label for="Class_size">1 - 10 Students</label><br>
          <input type="radio" id="Class_size" name="Class_size" value="small">
          <label for="Class_size">11 - 25 Students</label><br>
          <input type="radio" id="Class_size" name="Class_size" value="med">
          <label for="Class_size">26 - 40 Students</label><br>
          <input type="radio" id="Class_size" name="Class_size" value="large">
          <label for="Class_size">40 - 60 Students</label><br>
          <input type="radio" id="Class_size" name="Class_size" value="any">
          <label for="Class_size">No Size Preference</label><br>
        </div>
        
        <label for="Group_size"><b> Individual Project Group Size Desired </b></label>
        <div class = "checklist">
          <input type="radio" id="Group_size" name="Group_size" value="tiny">
          <label for="Group_size">1 Student</label><br>
          <input type="radio" id="Group_size" name="Group_size" value="small">
          <label for="Group_size">2 - 4 Students</label><br>
          <input type="radio" id="Group_size" name="Group_size" value="med">
          <label for="Group_size">5 - 8 Students</label><br>
          <input type="radio" id="Group_size" name="Group_size" value="large">
          <label for="Group_size">8 - 12 Students</label><br>
          <input type="radio" id="Group_size" name="Group_size" value="any">
          <label for="Group_size">No Size Preference</label><br>
        </div>

        <label for="Level"><b>Desired Student Level </b></label>
        <p>(Select all that apply)</p>
        <div class="checklist">
          <input type="checkbox" id="Level" name="Level" value="E">
          <label for="Level"> Elementary School </label><br>
          <input type="checkbox" id="Level" name="Level" value="M">
          <label for="Level"> Middle School </label><br>
          <input type="checkbox" id="Level" name="Level" value="H">
          <label for="Level"> High School </label><br>
          <input type="checkbox" id="Level" name="Level" value="U">
          <label for="Level"> Undergraduate </label><br>
          <input type="checkbox" id="Level" name="Level" value="G">
          <label for="Level"> Graduate </label><br>
        </div>
        
        <label for="Hours_estimated"><b> Estimated Time Commitment </b></label>
        <p> The number of hours each individual project group might take to complete the tasks. </p>
        <input type="number" id="Hours_estimated" name="Hours_estimated" min="0" max="100" placeholder="Enter number of hours est." required><br>
        
        <label for="Locations"><b>Project Location(s) </b></label>
        <p> Can virtual be supported? </p>
        <input type="checkbox" id="Virtual" name="Virtual" value="Yes">
        <label for="Virtual"> Yes virtual.</label>
        <input type="checkbox" id="Virtual" name="Virtual" value="No">
        <label for="Virtual"> No virtual. </label><br>
        <input type="text" id="Locations" name="Locations" placeholder="Enter zip code(s), separated by commas." required>
        
        <label for="Start_date"><b> Desired Dates </b> (Optional)</label><p></p>
        <label for="Start_date">Start Date: </label>
        <input type="date" id="Start_date" name="Start_date" value="2021-01-01"> <br><br>
        <label for="End_date"> End Date:</label>
        <input type="date" id="End_date" name="End_date" value="2022-01-01"> <br><br>
      </div>

      <button type="submit" class="registerbtn">Create Project</button>
      
    </form>
    
    
  </body>
  
  
  
  </html>

Backend/edtech/createproject/templates/createproject/partner_home.html
<!DOCTYPE html>
<html lang="en">

<!-- Jquery scripts -->
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>

<head>
    <meta charset="ut 8">
    {% load static %}
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>Partner Home</title>
</head>

<body>
    
    <div class = "wrapper">
        <div class = "nav-bar" id = "partner-nav-bar">
            <h1 class="header"> WeMinari </h1>
            <ul>
                <p></p>
                <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
                <li><a href="{% url 'createproject:index' %}">Create New Project</a></li>
                <li><a href="{% url 'createproject:home' %}">Home</a></li>
            </ul>
        </div>
    </div>
    
    <!-- Header -->
    <div class ="title">
        <h1> Welcome, KevinCo. </h1>
    </div>
    
    <!-- Grid -->
    <h2 class="header"> Matched Projects </h2>
    <p class="description"> These projects have been matched with a class.</p>
    <div class="ongoing-projects">
        {% if project_list %}
        <ul>
            {% for proj in project_list %}
                {% if proj.ClassNum == 1 %}
                <h3>{{ proj.Partner}}: {{ proj.Title }}</h3>
                <p><strong>{{proj.Start_date}} to {{proj.End_date}}</strong></p>
                <p style="font-style:italic"><strong>Locations:</strong> {{ proj.Locations}}</p>
                {% if proj.Virtual == "Yes" %}
                <p> Virtual is supported. </p>
                {% endif %}
                <p>{{ proj.Short }}</p>
                <li>Subject(s): {{proj.Subjects}}</li>
                <li>Desired Level: {{ proj.Level }}</li>
                <li>Desired Class Size: {{ proj.Class_size }}</li>
                <li>Desired Group Size: {{ proj.Group_size }}</li>
                <form action="{% url 'createproject:proj_detail' proj.id %}" method="GET">
                    <button type="submit" class="selector">Go to Page</button>
                </form>
                <div class="spacer"><hr></div>
                {% endif %}
            {% endfor %}
        </ul>
        {% else %}
            <p>No matches yet!</p>
        {% endif %}  
    </div>
    
    <div class="spacer"></div>
    
    <h2 class="header"> Unmatched Projects </h2>
    
    <div class="ongoing-projects">
        {% if project_list %}
        <ul>
            {% for proj in project_list %}
                {% if proj.ClassNum == 0 %}
                <h3>{{ proj.Partner}}: {{ proj.Title }}</h3>
                <p><strong>{{proj.Start_date}} to {{proj.End_date}}</strong></p>
                <p style="font-style:italic"><strong>Locations:</strong> {{ proj.Locations}}</p>
                {% if proj.Virtual == "Yes" %}
                <p> Virtual is supported. </p>
                {% endif %}
                <p>{{ proj.Long }}</p>
                <li>Subject(s): {{proj.Subjects}}</li>
                <li>Desired Level: {{ proj.Level }}</li>
                <li>Desired Class Size: {{ proj.Class_size }}</li>
                <li>Desired Group Size: {{ proj.Group_size }}</li>
                <div class="spacer"><hr></div>
                {% endif %}
            {% endfor %}
        </ul>
        {% else %}
            <p>No unmatched projects.</p>
        {% endif %} 
    </div>
    
    <div class="spacer"></div>
    
    
</body>



</html>

Backend/edtech/createproject/templates/createproject/proj_detail.html
<!DOCTYPE html>
<html lang="en">

<!-- Jquery scripts -->
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>

<head>
    <meta charset="ut 8">
    {% load static %}
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>Project Detail Page</title>
</head>

<body>
    
    <div class = "wrapper">
        <div class = "nav-bar" id = "partner-nav-bar">
            <h1 class="header"> WeMinari </h1>
            <ul>
                <p></p>
                <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
                <li><a href="{% url 'createproject:index' %}">Create New Project</a></li>
                <li><a href="{% url 'createproject:home' %}">Home</a></li>
            </ul>
        </div>
    </div>
    
    <!-- Header -->
    <div class ="title">
        <h1> Detail Page: {{proj.Partner}}: {{proj.Title}} </h1>
    </div>
    
    <div class = "projinfo">
        <p style="font-style: italic">{{ proj.Short }} </p>
        <p><strong>{{proj.Start_date}} to {{proj.End_date}}</strong></p>
        <p style="font-style:italic"><strong>Locations:</strong> {{ proj.Locations}}</p>
        {% if proj.Virtual == "Virtual" %}
        <p> Virtual is supported. </p>
        {% endif %}
        
        <p>{{ proj.Long }}</p>
        <li>Subject(s): {{proj.Subjects}}</li>
        <li>Desired Level: {{ proj.Level }}</li>
        <li>Desired Class Size: {{ proj.Class_size }}</li>
        <li>Desired Group Size: {{ proj.Group_size }}</li>
    </div>
    
    
    <div class="spacer"><hr></div>
    
    <h2 class="header"> Discussion Board </h2>
    
    <div class="ongoing-projects">
        {% if latest_posts %}
          <ul>
            {% for post in latest_posts %}
            <div class="grid-container">
              <div class = "grid-child">

                {% if post.Role == "Partner" %}
                <div class="InstructorPost">
                  <h3> PARTNER POST : {{post.Author}} </h3>
                  <p> {{post.PostDate}} </p>
                  <p> {{post.Body}} </p>
                </div>
                
                {% else %}
                <div>
                  <h3> {{post.Author}} </h3>
                  <p> {{post.PostDate}} </p>
                  <p> {{post.Body}} </p>
                </div>
                
                {% endif %}
              </div>
              <div class="grid-child">
                {% if post.Role == "Partner" %}
                  <img src= "{% static 'img/teacher.png' %}" height="50px">
                {% else %}
                <img src= "{% static 'img/student.jpg' %}" height="50px">
                {% endif %}
              </div>
            </div>
            <div class="spacer"><hr></div>
            {% endfor %}
          </ul>
          {% else %}
          <p>You and the class haven't been very active. Get the conversation started!</p>
          {% endif %}
    </div>
    <div class = "add-post">
        <form action="{% url 'addpost:createprojpost' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="Author" value="KevinCo">
          <input type="hidden" name="Role" value="Partner">
          <input type="hidden" name="ProjKey" value={{proj.id}}>
          <textarea rows = "5" name="Body" placeholder="Share something with the class!" maxlength="1000" required></textarea>
          
          <button type="submit" class="registerbtn">Add Post</button>
          
        </form>
      </div>
    
    <div class="spacer"></div>
    
    
</body>



</html>

Backend/edtech/createproject/templates/createproject/results.html
<!DOCTYPE html>
<html lang="en">

<!-- Jquery scripts -->
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>

<head>
    <meta charset="ut 8">
    {% load static %}
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>Matching Forum</title>
</head>

<body>
    
    <div class = "wrapper">
		<div class = "nav-bar" id = "teach-nav-bar">
			<h1 class="header"> WeMinari </h1>
			<ul>
				<p></p>
                <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
				<li><a href="{% url 'createclass:index' %}">Create Class</a></li>
				<li><a href="{% url 'createproject:results' %}">Project Forum</a></li>
				<li><a href="{% url 'createclass:home' %}">Home</a></li>
			</ul>
		</div>
    </div>
    
    <!-- Header -->
    <div class ="title">
        <h1> Find Your Projects. </h1>
    </div>
    
    <!-- Grid -->
    <div class="grid-container">
        
        <!-- Student Snapshot -->
        <div class="grid-child">
            <h2 class="header"> Available Opportunities </h2>
            <div class="forum">
                {% for proj in project_list %}
                <h3>{{ proj.Partner}}: {{ proj.Title }}</h3>
                <p><strong>{{proj.Start_date}} to {{proj.End_date}}</strong></p>
                <p style="font-style:italic"><strong>Locations:</strong> {{ proj.Locations}}</p>
                {% if proj.Virtual == "Yes" %}
                <p> Virtual is supported. </p>
                {% endif %}
                <p>{{ proj.Short }}</p>
                <li>Subject(s): {{proj.Subjects}}</li>
                <li>Desired Level: {{ proj.Level }}</li>
                <li>Desired Class Size: {{ proj.Class_size }}</li>
                <li>Desired Group Size: {{ proj.Group_size }}</li>
                <form action="{% url 'createproject:addprojtoclass' proj.id %}" method="POST">
                    {% csrf_token %}
                    <!-- <input type="hidden" name="Title" value="{{proj.id}}"> -->
                    <input type="submit" class="selector" value="Add This Project">
                  </form>
                <hr>
                {% endfor %}
            </div>
        </div>
        
        <!-- Partner List -->
        <div class="grid-child">
            <h2 class="header"> Filters </h2>
            <div class="filters">
                <form action="" method="GET">
                    <label for="partner_name"><b>Partner Name</b></label>
                    <input type="text" placeholder="Filter by Partner" name="Partner" id="Partner">

                    <label for="Subjects"><b>Subjects </b></label>
                    <p>(Select all that apply)</p>
                    <div class="checklist">
                        <input type="checkbox" id="Subjects" name="Subjects" value="ES">
                        <label for="Subjects"> Environmental Sustainability </label><br>
                        <input type="checkbox" id="Subjects" name="Subjects" value="MA">
                        <label for="Subjects"> Mathematics </label><br>
                        <input type="checkbox" id="Subjects" name="Subjects" value="B">
                        <label for="Subjects"> Biology </label><br>
                        <input type="checkbox" id="Subjects" name="Subjects" value="C">
                        <label for="Subjects"> Chemistry </label><br>
                        <input type="checkbox" id="Subjects" name="Subjects" value="P">
                        <label for="Subjects"> Physics </label><br>
                        <input type="checkbox" id="Subjects" name="Subjects" value="ME">
                        <label for="Subjects"> Mechanical Engineering </label><br>
                        <input type="checkbox" id="Subjects" name="Subjects" value="CS">
                        <label for="Subjects"> Computer Science </label><br>
                    </div>
                    
                    <label for="Level"><b>Desired Student Level </b></label>
                    <p>(Select all that apply)</p>
                    <div class="checklist">
                        <input type="checkbox" id="Level" name="Level" value="E">
                        <label for="Level"> Elementary School </label><br>
                        <input type="checkbox" id="Level" name="Level" value="M">
                        <label for="Level"> Middle School </label><br>
                        <input type="checkbox" id="Level" name="Level" value="H">
                        <label for="Level"> High School </label><br>
                        <input type="checkbox" id="Level" name="Level" value="U">
                        <label for="Level"> Undergraduate </label><br>
                        <input type="checkbox" id="Level" name="Level" value="G">
                        <label for="Level"> Graduate </label><br>
                    </div>
                    
                    <label for="Start_date"><b> Start Day Range </b></label><p></p>
                    <label for="Start_date">As Early As: </label>
                    <input type="date" id="Start_date_0" name="Start_date_0" value="2021-01-01"> <br><br>
                    <label for="Start_date">As Late As: </label>
                    <input type="date" id="Start_date_1" name="Start_date_1" value="2022-01-01"> <br><br>
                    
                    <input type="submit" class="registerbtn" value="Filter">
                </form>
            </div>
        </div>
    </div>
    
    <div class="spacer"><br></div>
    
    <div class="spacer"><br></div>
    
    
</body>



</html>

Backend/edtech/createproject/templates/createproject/student_proj_detail.html
<!DOCTYPE html>
<html lang="en">

<!-- Jquery scripts -->
<script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>

<head>
    <meta charset="ut 8">
    {% load static %}
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>Project Detail Page</title>
</head>

<body>
    
    <div class = "wrapper">
        <div class = "nav-bar" id = "student-nav-bar">
            <h1 class="header"> WeMinari </h1>
            <ul>
              <p></p>
              <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
              <li><a href="{% url 'scrapenews:cognitive_questionnaire' %}">Cognitive Quiz</a></li>
              <li><a href="{% url 'scrapenews:index2' %}">Home (Cozy)</a></li>
              <li><a href="{% url 'scrapenews:index' %}">Home (Full)</a></li>
            </ul>
        </div>
    </div>
    
    <!-- Header -->
    <div class ="title">
        <h1> Detail Page - {{proj.Partner}}: {{proj.Title}} </h1>
    </div>
    
    <div class = "projinfo">
        <p style="font-style: italic">{{ proj.Short }} </p>
        <p><strong>{{proj.Start_date}} to {{proj.End_date}}</strong></p>
        <p style="font-style:italic"><strong>Locations:</strong> {{ proj.Locations}}</p>
        {% if proj.Virtual == "Yes" %}
        <p> Virtual is supported. </p>
        {% endif %}
        
        <p>{{ proj.Long }}</p>
        <li>Subject(s): {{proj.Subjects}}</li>
        <li>Desired Level: {{ proj.Level }}</li>
        <li>Desired Class Size: {{ proj.Class_size }}</li>
        <li>Desired Group Size: {{ proj.Group_size }}</li>
    </div>
    
    
    <div class="spacer"><hr></div>
    
    <h2 class="header"> Discussion Board </h2>
    
    <div class="ongoing-projects">
        {% if latest_posts %}
          <ul>
            {% for post in latest_posts %}
            <div class="grid-container">
              <div class = "grid-child">

                {% if post.Role == "Partner" %}
                <div class="InstructorPost">
                  <h3> PARTNER POST : {{post.Author}} </h3>
                  <p> {{post.PostDate}} </p>
                  <p> {{post.Body}} </p>
                </div>
                
                {% else %}
                <div>
                  <h3> {{post.Author}} </h3>
                  <p> {{post.PostDate}} </p>
                  <p> {{post.Body}} </p>
                </div>
                
                {% endif %}
              </div>
              <div class="grid-child">
                {% if post.Role == "Partner" %}
                  <img src= "{% static 'img/teacher.png' %}" height="50px">
                {% else %}
                <img src= "{% static 'img/student.jpg' %}" height="50px">
                {% endif %}
              </div>
            </div>
            <div class="spacer"><hr></div>
            {% endfor %}
          </ul>
          {% else %}
          <p>You and the class haven't been very active. Get the conversation started!</p>
          {% endif %}
    </div>
    <div class = "add-post">
        <form action="{% url 'addpost:createprojpost' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="Author" value="Kevin">
          <input type="hidden" name="Role" value="Student">
          <input type="hidden" name="ProjKey" value={{proj.id}}>
          <textarea rows = "5" name="Body" placeholder="Share something with the class!" maxlength="1000" required></textarea>
          
          <button type="submit" class="registerbtn">Add Post</button>
          
        </form>
      </div>
    
    <div class="spacer"></div>
    
    
</body>



</html>