Backend/edtech/addpost/urls.py
from django.urls import path

from . import views

app_name = 'addpost'
urlpatterns = [
    path('createpost/', views.createpost, name='createpost'),
    path('createprojpost/', views.createprojpost, name='createprojpost'),
]

Backend/edtech/createclass/urls.py
from django.urls import path

from . import views

app_name = 'createclass'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('create_new_class/', views.create_new_class, name='create_new_class'),
    path('<int:post_id>/deletepost/', views.deletepost, name='deletepost'),
    path('<int:proj_id>/removeproj/', views.removeproj, name='removeproj'),
]

Backend/edtech/createproject/urls.py
from django.urls import path

from . import views

app_name = 'createproject'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('create_new_project/', views.create_new_project, name='create_new_project'),
    path('<int:proj_id>/addprojtoclass/', views.addprojtoclass, name='addprojtoclass'),
    path('home/', views.home, name='home'),
    path('<int:proj_id>/proj_detail/', views.proj_detail, name='proj_detail'),
    path('<int:proj_id>/student_proj_detail/', views.student_proj_detail, name='student_proj_detail'),
]

Backend/edtech/edtech/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('addpost/', include('addpost.urls')),
    path('createproject/', include('createproject.urls')),
    path('createclass/', include('createclass.urls')),
    path('scrapenews/', include('scrapenews.urls')),
    path('admin/', admin.site.urls),
]

Backend/edtech/scrapenews/urls.py
from django.urls import path

from . import views

app_name = 'scrapenews'
urlpatterns = [
    path('home', views.index, name='index'),
    path('home2', views.index2, name='index2'),
    path('log_link/', views.log_link, name='log_link'),
    path('cognitivehome/', views.cognitivehome, name='cognitivehome'),
    path('cognitive_questionnaire/', views.cognitive_questionnaire, name='cognitive_questionnaire'),
    path('demo_home',views.demo_home, name='demo_home'),
]

Backend/edtech/createclass/models.py
from django.db import models
from django.forms import ModelForm
from django import forms

# Create your models here.
class Classrooms(models.Model):
    def __str__(self):
        return self.Name
    Name = models.CharField(max_length=255)
    Description = models.CharField(max_length=500)
    Subjects = models.CharField(max_length=255)
    Syllabus = models.TextField()
    Student_emails = models.TextField()


SUBJECTS = (
    ('ES','Environmental'),
    ('MA', 'Math'),
    ('B', 'Biology'),
    ('C', 'Chemistry'),
    ('P', 'Physics'),
    ('ME', 'Mechanical'),
    ('CS', 'Computer Science')
)
class CreateClassForm(ModelForm):
    Subjects = forms.MultipleChoiceField(choices = SUBJECTS)
    class Meta:
        model = Classrooms
        fields = '__all__'

Backend/edtech/createclass/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Classrooms, CreateClassForm
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from createproject.models import Projects
from addpost.models import PostList

# Create your views here.
def index(request):
#     project_list = Projects.objects.order_by('-Start_date')
#     context = {'project_list': project_list}
    return render(request, 'createclass/index.html')

def home(request):
    project_list = Projects.objects.filter(ClassNum = 1).order_by('-Start_date')
    latest_posts = PostList.objects.order_by('-PostDate')[0:30]
    context = {'project_list': project_list, 'latest_posts': latest_posts}
    return render(request, 'createclass/home.html', context)


def create_new_class(request):
    context = {}
    form = CreateClassForm(request.POST or None)

    print(form)
    if form.is_valid():
        form.save()

    context['form'] = form
    return HttpResponseRedirect(reverse('createclass:home'))

def deletepost(request, post_id):
    post = get_object_or_404(PostList, pk=post_id)
    post.delete()

    return HttpResponseRedirect(reverse('createclass:home'))

def removeproj(request, proj_id):
    proj = get_object_or_404(Projects, pk=proj_id)
    proj.ClassNum = 0
    proj.save()

    return HttpResponseRedirect(reverse('createclass:home'))

Backend/edtech/createclass/templates/createclass/home.html
  <!DOCTYPE html>
  <html lang="en">
  
  <!-- Jquery scripts -->
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  
  <head>
	<meta charset="ut 8">
	{% load static %}
	<link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
	<title>Instructor Landing Page</title>
</head>

<body>
	
	<div class = "wrapper">
		<div class = "nav-bar" id = "teach-nav-bar">
			<h1 class="header"> WeMinari </h1>
			<ul>
				<p></p>
				<li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
				<li><a href="{% url 'createclass:index' %}">Create Class</a></li>
				<li><a href="{% url 'createproject:results' %}">Project Forum</a></li>
				<li><a href="{% url 'createclass:home' %}">Home</a></li>
			</ul>
		</div>
	</div>
	
	<!-- Header -->
	<div class ="title">
		<h1> Hi, Mr. Cheng. This is Your Classroom. </h1>
	</div>
	
	<!-- Grid -->
	<div class="instructor-partner">
		
		<!-- Student Snapshot -->
		<h2 class="header"> Student Snapshot </h2>
		<hr>
		<table style="width:100%">
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Cognitive Model</th>
				<th>Saved Article Count</th>
				<th>Favorite Topics</th>
				<th>Number of Posts</th>
			</tr>
			<tr>
				<td>Kevin</td>
				<td>Cheng</td>
				<td>Field Independent</td>
				<td>42</td>
				<td>solar wind energy</td>
				<td>101</td>
			</tr>
		</table>

	</div>
	
	<div class="spacer"></div>
	
	<h2 class="header"> To-Do and For Your Review </h2>
	
	<div class="to-do">
		{% if latest_posts %}
		<ul>
			{% for post in latest_posts %}
			
			{% if post.Role == "Instructor" %}
			<div class="InstructorPost">
				<h3> FROM THE TEACHER'S DESK : {{post.Author}} </h3>
				<p> {{post.PostDate}} </p>
				<p> {{post.Body}} </p>
			</div>
			
			{% else %}
			<div>
				<h3> {{post.Author}} </h3>
				<p> {{post.PostDate}} </p>
				<p> {{post.Body}} </p>
			</div>
			
			{% endif %}
			<form action="{% url 'createclass:deletepost' post.id %}" method="POST">
				{% csrf_token %}
				<input type="submit" class="selector" style="background-color: red; border-color: red;" value="Delete Post">
			</form>
			<hr>
			
			{% endfor %}
		</ul>
		{% else %}
		<p>Your class hasn't been very active. Get the conversation started!</p>
		{% endif %}
	</div>
	
	<div class="spacer"></div>
	
	<h2 class="header"> Project List </h2>
	
	<div class="instructor-partner">
		{% for proj in project_list %}
		<h3>{{proj.Partner}}: {{ proj.Title }}</h3>
		<p><strong>{{proj.Start_date}} to {{proj.End_date}}</strong></p>
		<p style="font-style:italic"><strong>Locations:</strong> {{ proj.Locations}}</p>
		{% if proj.Virtual == "Yes" %}
		<p> Virtual is supported. </p>
		{% endif %}
		<p>{{ proj.Short }}</p>

		<form action="{% url 'createclass:removeproj' proj.id %}" method="POST">
			{% csrf_token %}
			<input type="submit" class="selector" value="Remove Project">
		</form>
		<hr>
		{% endfor %}
	</div>
	
	<div class="spacer"></div>
	
	<h2 class="header"> Make an Announcement </h2>
	
	<div class = "add-post">
		<form action="{% url 'addpost:createpost' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" name="Author" value="Mr. Cheng">
			<input type="hidden" name="Role" value="Instructor">
			<textarea rows = "5" name="Body" placeholder="Share something with your class!" maxlength="1000"></textarea>
			
			<button type="submit" class="registerbtn">Add Post</button>
			
		</form>
	</div>
	
	
</body>



</html>

Backend/edtech/createclass/templates/createclass/index.html
  <!DOCTYPE html>
  <html lang="en">

  <!-- Jquery scripts -->
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <!-- <script src='../Common/app.js'></script> -->

  <head>
  	<meta charset="ut 8">
  	{% load static %}
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
  	<title>Create Classroom</title>
  </head>

  <body>

  	<div class = "wrapper">
      <div class = "nav-bar" id = "teach-nav-bar">
        <h1 class="header"> WeMinari </h1>
        <ul>
          <p></p>
          <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
          <li><a href="{% url 'createclass:index' %}">Create Class</a></li>
          <li><a href="{% url 'createproject:results' %}">Project Forum</a></li>
          <li><a href="{% url 'createclass:home' %}">Home</a></li>
        </ul>
      </div>
  	</div>

  	<!-- Header -->
  	<div class ="title">
  		<h1> Create Your Classroom, Mr. Cheng. </h1>
  	</div>

  	<form action="create_new_class/" method="POST">
      {% csrf_token %}
      <div class="container">
        <!-- <h1>Register</h1> -->
        <p>Please fill in this form to create a classroom.</p>
        <hr>

        <label for="Name"><b>Classroom Name</b></label>
        <input type="text" placeholder="Enter Class Name" name="Name" id="Name" required>

        <label for="Description"><b>Short Classroom Description</b></label>
        <textarea rows = "5"  name = "Description" placeholder="Enter Class Details (Max 500 Char)." maxlength="500" required></textarea><br>

        <label for="Subjects"><b>Subjects </b></label>
        <p>(Select all that apply)</p>
        <div class="checklist">
          <input type="checkbox" id="Subjects" name="Subjects" value="ES">
          <label for="Subjects"> Environmental Sustainability </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="M">
          <label for="Subjects"> Mathematics </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="B">
          <label for="Subjects"> Biology </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="C">
          <label for="Subjects"> Chemistry </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="P">
          <label for="Subjects"> Physics </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="ME">
          <label for="Subjects"> Mechanical Engineering </label><br>
          <input type="checkbox" id="Subjects" name="Subjects" value="CS">
          <label for="Subjects"> Computer Science </label><br>
        </div>

        <label for="Syllabus"><b>Syllabus</b></label>
        <p> Enter your syllabus below.</p>
        <!-- <input type="file" id="syllabus" name="syllabus"><p></p> -->
        <textarea rows = "5" name="Syllabus" placeholder="Enter syllabus here." maxlength="10000"></textarea>

        <label for="Student_emails"><b> Add Students to Your Class</b></label>
        <p> Manually enter student emails below.</p>
        <!-- <input type="file" id="emailfile" name="emailfile"><p></p> -->
        <!-- <textarea rows = "3" id="Student_emails" name="Student_emails" placeholder="Valid student emails, seperated by commas."></textarea> -->
        <textarea rows = "3"  name = "Student_emails" placeholder="Valid student emails, seperated by commas." maxlength="500" required></textarea><br>


        <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>
        <button type="submit" class="registerbtn">Register</button>
      </div>

      <div class="container signin">
        <p>Already have an account? <a href="#">Sign in</a>.</p>
      </div>
    </form>


  </body>



  </html>