Backend/edtech/addpost/urls.py
from django.urls import path

from . import views

app_name = 'addpost'
urlpatterns = [
    path('createpost/', views.createpost, name='createpost'),
    path('createprojpost/', views.createprojpost, name='createprojpost'),
]

Backend/edtech/createclass/urls.py
from django.urls import path

from . import views

app_name = 'createclass'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('create_new_class/', views.create_new_class, name='create_new_class'),
    path('<int:post_id>/deletepost/', views.deletepost, name='deletepost'),
    path('<int:proj_id>/removeproj/', views.removeproj, name='removeproj'),
]

Backend/edtech/createproject/urls.py
from django.urls import path

from . import views

app_name = 'createproject'
urlpatterns = [
    path('', views.index, name='index'),
    path('results/', views.results, name='results'),
    path('create_new_project/', views.create_new_project, name='create_new_project'),
    path('<int:proj_id>/addprojtoclass/', views.addprojtoclass, name='addprojtoclass'),
    path('home/', views.home, name='home'),
    path('<int:proj_id>/proj_detail/', views.proj_detail, name='proj_detail'),
    path('<int:proj_id>/student_proj_detail/', views.student_proj_detail, name='student_proj_detail'),
]

Backend/edtech/edtech/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('addpost/', include('addpost.urls')),
    path('createproject/', include('createproject.urls')),
    path('createclass/', include('createclass.urls')),
    path('scrapenews/', include('scrapenews.urls')),
    path('admin/', admin.site.urls),
]

Backend/edtech/scrapenews/urls.py
from django.urls import path

from . import views

app_name = 'scrapenews'
urlpatterns = [
    path('home', views.index, name='index'),
    path('home2', views.index2, name='index2'),
    path('log_link/', views.log_link, name='log_link'),
    path('cognitivehome/', views.cognitivehome, name='cognitivehome'),
    path('cognitive_questionnaire/', views.cognitive_questionnaire, name='cognitive_questionnaire'),
    path('demo_home',views.demo_home, name='demo_home'),
]

Backend/edtech/scrapenews/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class NewsList(models.Model):
    def __str__(self):
        return self.Title
    Title = models.TextField()
    Summary = models.TextField()
    Image = models.TextField()
    Link = models.TextField()
    Date = models.TextField()
    Site = models.TextField()

class ArticlesClicked(models.Model):
    def __str__(self):
        return self.Title
    Title = models.TextField()
    Summary = models.TextField()
    Image = models.TextField()
    Link = models.TextField()
    Date = models.TextField()
    Site = models.TextField()


class ArticlesClickedForm(ModelForm):
    class Meta:
        model = ArticlesClicked
        fields = '__all__'

Backend/edtech/scrapenews/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import NewsList, ArticlesClickedForm
from addpost.models import PostList
from createproject.models import Projects
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime

# Create your views here.
def demo_home(request):
    return render(request, 'scrapenews/demo_home.html')

def index(request):
    for Link in NewsList.objects.values_list('Link', flat=True).distinct():
        NewsList.objects.filter(pk__in=NewsList.objects.filter(Link=Link).values_list('id', flat=True)[1:]).delete()
    latest_news_list = NewsList.objects.order_by('-Date')[0:30]
    latest_posts = PostList.objects.order_by('-PostDate')[0:30]
    project_list = Projects.objects.filter(ClassNum = 1).order_by('-Start_date')
    context = {'latest_news_list': latest_news_list, 'latest_posts': latest_posts, 'project_list':project_list}
    return render(request, 'scrapenews/index.html', context)

def index2(request):
    for Link in NewsList.objects.values_list('Link', flat=True).distinct():
        NewsList.objects.filter(pk__in=NewsList.objects.filter(Link=Link).values_list('id', flat=True)[1:]).delete()
    latest_news_list = NewsList.objects.order_by('-Date')[0:30]
    latest_posts = PostList.objects.order_by('-PostDate')[0:30]
    project_list = Projects.objects.filter(ClassNum = 1).order_by('-Start_date')
    context = {'latest_news_list': latest_news_list, 'latest_posts': latest_posts, 'project_list':project_list}
    
    return render(request, 'scrapenews/index2.html', context)

def log_link(request):
    context = {}
    form = ArticlesClickedForm(request.POST or None)
    #form['DateClicked'] = datetime.today().strftime('%Y/%m/%d')

    if form.is_valid():
        form.save()

    context['form'] = form
    return HttpResponseRedirect(reverse('scrapenews:index'))

def cognitive_questionnaire(request):
    return render(request, 'scrapenews/cognitive.html')

def cognitivehome(request):
    answers = request.GET
    fi = 0
    fd = 0
    print(answers)
    for key in answers:
        if answers[key] == "fi":
            fi += 1
        else:
            fd += 1
    
    if fi > fd:
        print('going to fi page', fd, fi)
        return HttpResponseRedirect(reverse('scrapenews:index'))
    else:
        print('going to fd page', fd, fi)
        return HttpResponseRedirect(reverse('scrapenews:index2'))

Backend/edtech/scrapenews/templates/scrapenews/cognitive.html
  <!DOCTYPE html>
  <html lang="en">
  
  <!-- Jquery scripts -->
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  
  
  <head>
    <meta charset="ut 8">
    {% load static %}
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>Student Cognitive Assessment</title>
  </head>
  
  <body>
    
    <div class = "wrapper">
      <div class = "nav-bar">
        <h1 class="header"> WeMinari </h1>
        <ul>
          <p></p>
          <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
          <li><a href="{% url 'scrapenews:cognitive_questionnaire' %}">Cognitive Quiz</a></li>
          <li><a href="{% url 'scrapenews:index2' %}">Home (Cozy)</a></li>
          <li><a href="{% url 'scrapenews:index' %}">Home (Full)</a></li>
        </ul>
      </div>
    </div>
    
    <!-- Header -->
    <div class ="title">
      <h1> What kind of a learner are you? </h1>
    </div>
    
    <!-- Grid -->
    <div class ="questionnaire">
      <p class="questionnaire">
        Every student has their own learning style. The goal is this app is to adapt to each individual's preferences and make learning as fun and easy as possible! We'll start here by
        filling out this questionnaire to determine some of your general learning and cognitive tendecies. The selected questions below are either curated from the 
        <a href="https://www.webtools.ncsu.edu/learningstyles/" target="_blank"> Index of Learning Styles (ILS) Questionnaire </a> or specifically designed to assess whether your
        cognitive style leans more towards field-dependent or field-independent. You can learn more from this <a href="https://www.jstor.org/stable/jeductechsoci.16.4.185 " target="_blank"> Journal of Educational Technology & Society</a>
        article (Hwang et al., 2013).
      </p>
      <div class="spacer"><p></p></div>
      
      <form action="{% url 'scrapenews:cognitivehome' %}" method="GET">
        <p>1. It's the end of a long day. Would you rather:</p>
        <input type="radio" name="q1" id="fd" value="fd" required>
        <label for="fd">Gather with a small group of friends.</label><br>
        <input type="radio" name="q1" id="fi" value="fi">
        <label for="fi">Stay home and relax.</label><br>
        <div class="spacer"><p></p></div>

        <p>2. When I am learning something new, it helps me to</p>
        <input type="radio" name="q2" id="fd" value="fd" required>
        <label for="fd">talk about it.</label><br>
        <input type="radio" name="q2" id="fi" value="fi">
        <label for="fi">think about it.</label><br>
        <div class="spacer"><p></p></div>

        <p>3. In classes I have taken</p>
        <input type="radio" name="q3" id="fi" value="fi" required>
        <label for="fi">  I have rarely gotten to know many of the students.</label><br>
        <input type="radio" name="q3" id="fd" value="fd">
        <label for="fd">  I have usually gotten to know many of the students.</label><br>
        <div class="spacer"><p></p></div>

        <p>4. It is more important to me that an instructor</p>
        <input type="radio" name="q4" id="fd" value="fd" required>
        <label for="fd">  lay out the material in clear sequential steps.</label><br>
        <input type="radio" name="q4" id="fi" value="fi">
        <label for="fi">give me an overall picture and relate the material to other subjects.</label><br>
        <div class="spacer"><p></p></div>

        <p>5. I learn</p>
        <input type="radio" name="q5" id="fd" value="fd" required>
        <label for="fd">  in fits and starts. I'll be totally confused and then suddenly it all "clicks."</label><br>
        <input type="radio" name="q5" id="fi" value="fi">
        <label for="fi"> at a fairly regular pace. If I study hard, I'll "get it."</label><br>
        <div class="spacer"><p></p></div>

        <p>6. I prefer to study </p>
        <input type="radio" name="q6" id="fd" value="fd" required>
        <label for="fd">in a study group.</label><br>
        <input type="radio" name="q6" id="fi" value="fi">
        <label for="fi">alone.</label><br>
        <div class="spacer"><p></p></div>

        <p>7. I would rather first</p>
        <input type="radio" name="q7" id="fi" value="fi" required>
        <label for="fi">  try things out.</label><br>
        <input type="radio" name="q7" id="fd" value="fd">
        <label for="fd">  think about how I'm going to do it.</label><br>
        <div class="spacer"><p></p></div>

        <p>8. When I have to perform a task, I prefer to</p>
        <input type="radio" name="q8" id="fd" value="fd" required>
        <label for="fd">master one way of doing it.</label><br>
        <input type="radio" name="q8" id="fi" value="fi">
        <label for="fi">come up with new ways of doing it.</label><br>
        <div class="spacer"><p></p></div>
        
        <p>9. When writing a paper, I am more likely to</p>
        <input type="radio" name="q9" id="fi" value="fi" required>
        <label for="fi">  work on (think about or write) different parts of the paper and then order them.</label><br>
        <input type="radio" name="q9" id="fd" value="fd">
        <label for="fd">  work on (think about or write) the beginning of the paper and progress forward.</label><br>
        <div class="spacer"><p></p></div>

        <p>10. When I have to work on a group project, I first want to</p>
        <input type="radio" name="q10" id="fi" value="fi" required>
        <label for="fi">   brainstorm individually and then come together as a group to compare ideas.</label><br>
        <input type="radio" name="q10" id="fd" value="fd">
        <label for="fd">  have "group brainstorming" where everyone contributes ideas.</label><br>
        <div class="spacer"><p></p></div>

        <p>11. When I am learning a new subject, I prefer to</p>
        <input type="radio" name="q11" id="fd" value="fd" required>
        <label for="fd">stay focused on that subject, learning as much about it as I can.</label><br>
        <input type="radio" name="q11" id="fi" value="fi">
        <label for="fi">try to make connections between that subject and related subjects.</label><br>
        <div class="spacer"><p></p></div>

        <p>12. I am more likely to be considered</p>
        <input type="radio" name="q12" id="fi" value="fi" required>
        <label for="fi">  reserved.</label><br>
        <input type="radio" name="q12" id="fd" value="fd">
        <label for="fd">  outgoing.</label><br>
        <div class="spacer"><p></p></div>

        <p>13. I like teachers</p>
        <input type="radio" name="q13" id="fd" value="fd" required>
        <label for="fd">who spend a lot of time explaining.</label><br>
        <input type="radio" name="q13" id="fi" value="fi">
        <label for="fi">  who put a lot of diagrams on the board.</label><br>
        <div class="spacer"><p></p></div>

        <p>14. I am more motivated by:</p>
        <input type="radio" name="q14" id="fi" value="fi" required>
        <label for="fi">  Competing with yourself and others to optimize results</label><br>
        <input type="radio" name="q14" id="fd" value="fd">
        <label for="fd">  Cooperating with others toward a common goal</label><br>
        <div class="spacer"><p></p></div>

        <p>15. When working, I prefer to:</p>
        <input type="radio" name="q15" id="fi" value="fi" required>
        <label for="fi">  multi-task.</label><br>
        <input type="radio" name="q15" id="fd" value="fd">
        <label for="fd">  focus on one thing at a time.</label><br>
        <div class="spacer"><p></p></div>

        
        
        <button type="submit" class="registerbtn">Submit</button>
        <div class="spacer"><p></p></div>
        
      </form>
    </div>
    
    
    
  </body>
  
  
  
  </html>

Backend/edtech/scrapenews/templates/scrapenews/demo_home.html
  <!DOCTYPE html>
  <html lang="en">
  
  <!-- Jquery scripts -->
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  
  
  <head>
    <meta charset="ut 8">
    {% load static %}
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>WeMinari</title>
  </head>
  
  <body>
    
    
    <div class = "jumbotron">
      <div class = "jumboheader">
        <a name="jumbo"></a>
        <br><br><br><br><br>
        <h1 id="welcome">Welcome to WeMinari.</h1>
        <div class="spacer"></div>
        <h2 style="color:black">Choose your role and take a tour:</h2>
        <button class="butt" id="studbutt"><a class="buttlink" href="{% url 'scrapenews:cognitive_questionnaire' %}">Student</a></button>
        <button class="butt" id="teachbutt"><a class="buttlink" href="{% url 'createclass:index' %}">Instructor</a></button>
        <button class="butt" id="partnerbutt"><a class="buttlink" href="{% url 'createproject:index' %}">Partner</a></button>
        <div class="spacer">
          <!-- <h3><a href="#about" style="color:green;text-decoration: none;margin-bottom: none;">About</a></h3> -->
          <i class="arrow down"><a href="#about" style="opacity: 0;">bb</a></i>
        </div>
      </div>
    </div>
    
    <a name="about"></a>
    <div class = "about">
      <h1 class="section-header">ABOUT WEMINARI</h1>
      <h3 style="font-style: italic;">Learning better, together.</h3>
      <p>Humans are social creatures. We learn best when we can work together and connect abstract concepts
        to real-life applications. WeMinari aims to provide a platform for students and instructors to
        collaborate together and apply their learnings in the real world. WeMinari's mission is to
        create a digital environment to foster an
        <strong>active, adaptive, social, and contextualized</strong> learning experience that connects classroom
        content with real-world context.
      </p>
      <h3 class="section-header" style="color:rgba(0, 156, 158, 1)">STUDENTS</h3>
      <p>
        WeMinari is designed to optimize the student's learning enjoyment and performance. 
        Their main feed is populated with news articles related to their coursework. As they use the app 
        more and save articles that they enjoyed, their main feed will <strong>adapt</strong> to their 
        behavior to meet their individualized interests.
      </p>
      <p>
        The UX is also designed to fit their learning style and cognitive learning model. A cognitive
        model questionnaire will direct them either to a cozy, minimalist view of their main landing page 
        for those who prefer less clutter, or to a full, info-packed view for those who prefer having
        everything in one, convenient location.
      </p>
        Students will also have exposure to opportunities outside of their classroom with external partners,
        like companies or community groups in their field of interest. This might come in the form of projects
        that students can work on, tours, or networking/recruiting events. In this way, students can engage
        with these partners to supplement their learning with <strong>active</strong> and 
        <strong>contextualized</strong> hands-on activities.
      <p>
      <p>
        While working on these projects or perusing their main feeds, students will want to share things, ask
        questions, or discuss ideas with their classmates, instructor, and external partners. WeMinari acts as a 
        social media app and learning management system combination to enable students to collaborate effectively
        in a responsible, engaging, and <strong>social</strong> manner.
      </p>
        
      </p>
      <h3 class="section-header" style="color:blue">INSTRUCTORS</h3>
      <p>
        Instructors are the head of the class. WeMinari empowers instructors to guide their classroom 
        without being too obtrusive. They can view key statistics on each student's performance and engagement
        in the app, look through available projects and other opportunities that they'd like to include
        as part of their curriculum, make announcements to their class, and moderate any online discussion
        that occurs in the app.
      </p>
      <h3 class="section-header" style="color:seagreen">PARTNERS</h3>
      <p>
        Last but not least, external partners can engage with a classroom as long as an instructor 
        initiates a connection. They'll have the ability to create projects, manage their projects, 
        and work with students on each individual project/opportunity that gets matched.
      </p>
      <h3 class="section-header"><a href="#jumbo" style="color:rgba(0, 156, 158, 1)">Let's get started!</a></h3>
    </div>
    
    
    
    
    
    
  </body>
  
  
  
  </html>

Backend/edtech/scrapenews/templates/scrapenews/index.html
  <!DOCTYPE html>
  <html lang="en">
  
  <!-- Jquery scripts -->
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  
  
  <head>
    <meta charset="ut 8">
    {% load static %}
    <script src="{% static 'scrapenews/app.js' %}"></script> 
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>Student Landing Page</title>
  </head>
  
  <body>
    
    <div class = "wrapper">
      <div class = "nav-bar">
        <h1 class="header"> WeMinari </h1>
        <ul>
          <p></p>
          <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
          <li><a href="{% url 'scrapenews:cognitive_questionnaire' %}">Cognitive Quiz</a></li>
          <li><a href="{% url 'scrapenews:index2' %}">Home (Cozy)</a></li>
          <li><a href="{% url 'scrapenews:index' %}">Home (Full)</a></li>
        </ul>
      </div>
    </div>
    
    <!-- Header -->
    <div class ="title">
      <h1> Welcome, Kevin. </h1>
    </div>
    
    <!-- Grid -->
    <div class="grid-container">
      
      <!-- Priority Feed -->
      <div class="grid-child">
        <h2 class="header"> Priority Feed </h2>
        <div class="priority">
          {% if latest_posts %}
          <ul>
            {% for post in latest_posts %}
            <div class="grid-container">
              <div class = "grid-child">
                
                {% if post.Role == "Instructor" %}
                <div class="InstructorPost">
                  <h3> FROM THE TEACHER'S DESK : {{post.Author}} </h3>
                  <p> {{post.PostDate}} </p>
                  <p> {{post.Body}} </p>
                </div>
                
                {% else %}
                <div>
                  <h3> {{post.Author}} </h3>
                  <p> {{post.PostDate}} </p>
                  <p> {{post.Body}} </p>
                </div>
                
                {% endif %}
              </div>
              <div class="grid-child">
                {% if post.Role == "Instructor" %}
                <img src= "{% static 'img/teacher.png' %}" height="50px">
                {% else %}
                <img src= "{% static 'img/student.jpg' %}" height="50px">
                {% endif %}
              </div>
            </div>
            <div class="spacer"><hr></div>
            {% endfor %}
          </ul>
          {% else %}
          <p>Your class hasn't been very active. Get the conversation started!</p>
          {% endif %}
        </div>
      </div>
      
      <!-- Partner List -->
      <div class="grid-child">
        <h2 class="header"> Project List </h2>
        <div class="partner-list">
          
          {% if project_list %}
          <!-- <ul> -->
            {% for proj in project_list %}
            <p><strong>{{proj.Partner}}: </strong>{{proj.Title}}</p>
            <form action="{% url 'createproject:student_proj_detail' proj.id %}" method="GET">
              <button type="submit" class="selector">Go to Page</button>
            </form>
            <hr style="margin-left:5%">
            {% endfor %}
          <!-- </ul> -->
          {% else %}
          <p>Stay tuned for more projects.</p>
          {% endif %}
          
        </div>
      </div>
      
      <div class="spacer"></div>
      <div class="spacer"></div>
      
      <!-- Main Feed -->
      <div class="grid-child">
        <h2 class="header"> Main Feed </h2>
        
        <div class="main-feed">
          {% if latest_news_list %}
          <ul>
            {% for article in latest_news_list %}
            <div class="grid-container">
              <div class="grid-child">
                <div class="news-article">
                  <h3>{{ article.Site }}</h3>
                  <h4><a href={{article.Link}} target="_blank">{{ article.Title }}</a></h4>
                  <p><strong>{{article.Date}}</strong></p>
                  <p class="short_snippet">{{article.Summary}}</p>
                </div>
              </div>
              <div class="grid-child">
                
                <img src="{{article.Image}}" height="100px" onerror="this.onerror=null;this.src='{% static 'img/ecobulb.ico' %}';">
                
                <form action="{% url 'scrapenews:log_link' %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="Title" value="{{article.Title}}">
                  <input type="hidden" name="Summary" value="{{article.Summary}}">
                  <input type="hidden" name="Image" value="{{article.Image}}">
                  <input type="hidden" name="Link" value="{{article.Link}}">
                  <input type="hidden" name="Date" value="{{article.Date}}">
                  <input type="hidden" name="Site" value="{{article.Site}}">
                  <input type="submit" class="selector" value="Save This Article">
                </form>
                
              </div>
            </div>
            <div class="spacer"><hr></div>
            {% endfor %}
          </ul>
          {% else %}
          <p>No articles are available.</p>
          {% endif %}
        </div>
      </div>
      
      <!-- Class and Schedule -->
      <div class="grid-child">
        <h2 class="header"> Your Class </h2>
        
        <div class="your-class">
          <p><strong>Mr. Cheng</strong></p>
          <p>Kevin</p>
        </div>
        <h2 class="header"> Upcoming </h2>
        <div class = "schedule">
          <p>No upcoming events.</p>
        </div>
      </div>
      
      
    </div>
    
    <div class="spacer"><br></div>
    
    <!-- Add a post -->
    <div class = "grid-child"></div>
    <h2 class="header"> Add a Post </h2>
    
    <div class = "add-post">
      <form action="{% url 'addpost:createpost' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="Author" value="Kevin">
        <input type="hidden" name="Role" value="Student">
        <textarea rows = "5" name="Body" placeholder="Share something with your class!" maxlength="1000" required></textarea>
        
        <button type="submit" class="registerbtn">Add Post</button>
        
      </form>
    </div>
    <div class="spacer"><br></div>
    
    
    
  </body>
  
  
  
  </html>

Backend/edtech/scrapenews/templates/scrapenews/index2.html
  <!DOCTYPE html>
  <html lang="en">
  
  <!-- Jquery scripts -->
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  
  
  <head>
    <meta charset="ut 8">
    {% load static %}
    <script src="{% static 'scrapenews/app.js' %}"></script> 
    <link rel='stylesheet' type="text/css" href="{% static 'css/global.css' %}">
    <title>Student Landing Page</title>
  </head>
  
  <body>
    
    <div class = "wrapper">
      <div class = "nav-bar">
        <h1 class="header"> WeMinari </h1>
        <ul>
          <p></p>
          <li><a href="{% url 'scrapenews:demo_home' %}">Demo Page</a></li>
          <li><a href="{% url 'scrapenews:cognitive_questionnaire' %}">Cognitive Quiz</a></li>
          <li><a href="{% url 'scrapenews:index2' %}">Home (Cozy)</a></li>
          <li><a href="{% url 'scrapenews:index' %}">Home (Full)</a></li>
        </ul>
      </div>
    </div>
    
    <!-- Header -->
    <div class ="title">
      <h1> Welcome, Kevin. </h1>
    </div>
    
    <!-- Grid -->
    <div class="container">
      
      <!-- Priority Feed -->
      <div class="grid-child">
        <h2 class="header"> Priority Feed </h2>
        <div class="priority">
          {% if latest_posts %}
          <ul>
            {% for post in latest_posts %}
            <div class="grid-container">
              <div class = "grid-child">

                {% if post.Role == "Instructor" %}
                <div class="InstructorPost">
                  <h3> FROM THE TEACHER'S DESK : {{post.Author}} </h3>
                  <p> {{post.PostDate}} </p>
                  <p> {{post.Body}} </p>
                </div>
                
                {% else %}
                <div>
                  <h3> {{post.Author}} </h3>
                  <p> {{post.PostDate}} </p>
                  <p> {{post.Body}} </p>
                </div>
                
                {% endif %}
              </div>
              <div class="grid-child">
                {% if post.Role == "Instructor" %}
                  <img src= "{% static 'img/teacher.png' %}" height="50px">
                {% else %}
                <img src= "{% static 'img/student.jpg' %}" height="50px">
                {% endif %}
              </div>
            </div>
            <div class="spacer"><hr></div>
            {% endfor %}
          </ul>
          {% else %}
          <p>Your class hasn't been very active. Get the conversation started!</p>
          {% endif %}
        </div>
      </div>

      <!-- Add a post -->
      <div class = "grid-child">
        <h2 class="header"> Add a Post </h2>
        
        <div class = "add-post">
          <form action="{% url 'addpost:createpost' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="Author" value="Kevin">
            <input type="hidden" name="Role" value="Student">
            <textarea rows = "5" name="Body" placeholder="Share something with your class!" maxlength="1000" required></textarea>
            
            <button type="submit" class="registerbtn">Add Post</button>
            
          </form>
        </div>
      </div>
      
      <!-- Main Feed -->
      <div class="grid-child">
        <h2 class="header"> Main Feed </h2>
        
        <div class="main-feed">
          {% if latest_news_list %}
          <ul>
            {% for article in latest_news_list %}
            <div class="grid-container">
              <div class="grid-child">
                <div class="news-article">
                  <h3>{{ article.Site }}</h3>
                  <h4><a href={{article.Link}} target="_blank">{{ article.Title }}</a></h4>
                  <p><strong>{{article.Date}}</strong></p>
                  <p class="short_snippet">{{article.Summary}}</p>
                </div>
              </div>
              <div class="grid-child">
                
                <img src="{{article.Image}}" height="100px" onerror="this.onerror=null;this.src='{% static 'img/ecobulb.ico' %}';">

                <form action="{% url 'scrapenews:log_link' %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="Title" value="{{article.Title}}">
                  <input type="hidden" name="Summary" value="{{article.Summary}}">
                  <input type="hidden" name="Image" value="{{article.Image}}">
                  <input type="hidden" name="Link" value="{{article.Link}}">
                  <input type="hidden" name="Date" value="{{article.Date}}">
                  <input type="hidden" name="Site" value="{{article.Site}}">
                  <input type="submit" class="selector" value="Save This Article">
                </form>

              </div>
            </div>
            <div class="spacer"><hr></div>
            {% endfor %}
          </ul>
          {% else %}
          <p>No articles are available.</p>
          {% endif %}
        </div>
      </div>
      
      
    </div>
    
    
    
  </body>
  
  
  
  </html>